---

- name: WIN_FILE | Ensure Directories are present for new VM
  delegate_to: data.DINOHEAD.NINJA
  vars_files:
    - environments/site-01/group_vars/windows.yml
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - C:\ClusterStorage\cluster-storage-01\vm\testVM
    - C:\ClusterStorage\cluster-storage-01\vm\testVM\Virtual Hard Disks
