---
hostvar:
  fqdn: tars.dinohead.ninja
  sdn: tars

  network:
    ip: 10.0.1.16
    subnet: 255.255.255.0
    dns: 10.0.1.2,10.0.1.22,10.0.1.222
    gateway: 10.0.1.1

  mount:
  - name: dev
    server: spok
    fqdn: spok.dinohead.ninja
    username: "{{ vault.domainUser }}"
    password: "{{ vault.password.text }}"
    domain: "{{ domain }}"
    permission: rw

  - name: file
    server: spok
    fqdn: spok.dinohead.ninja
    username: "{{ vault.domainUser }}"
    password: "{{ vault.password.text }}"
    domain: "{{ domain }}"
    permission: rw

  - name: video
    server: spok
    fqdn: spok.dinohead.ninja
    username: "{{ vault.domainUser }}"
    password: "{{ vault.password.text }}"
    domain: "{{ domain }}"
    permission: rw

  - name: backup
    server: T1000
    fqdn: t1000.dinohead.ninja
    username: "{{ vault.domainUser }}"
    password: "{{ vault.password.text }}"
    domain: "{{ domain }}"
    permission: rw

  rpms:
<<<<<<< HEAD
=======
  - gitflow
  - mtdev-devel
  - mtdev
  - xorg-x11-server-devel
  - google-chrome
  - slack
>>>>>>> 94116fd04a1f4b06dd060fbaaa208291a53d934a
  - ElectricFence
  - OpenEXR-libs
  - PyQt4
  - PyQt4-devel
  - SDL
  - SDL-devel
  - aeidon
  - akonadi
  - alex
  - alsa-lib-devel
  - ant
  - apache-commons-codec
  - apache-commons-lang
  - apache-commons-logging
  - apr-devel
  - apr-util-devel
  - aqbanking
  - at-spi2-atk-devel
  - at-spi2-core-devel
  - atk-devel
  - attica
  - attica-devel
  - audit-libs-devel
  - automoc
  - avalon-framework
  - avalon-logkit
  - babel
  - binutils-devel
  - boost
  - boost-atomic
  - boost-chrono
  - boost-context
  - boost-devel
  - boost-filesystem
  - boost-graph
  - boost-locale
  - boost-math
  - boost-program-options
  - boost-python
  - boost-random
  - boost-regex
  - boost-serialization
  - boost-signals
  - boost-test
  - boost-timer
  - boost-wave
  - bzip2-devel
  - bzr
  - c-ares-devel
  - cabal-install
  - cairo-devel
  - cairo-gobject-devel
  - ccache
  - check
  - check-devel
  - chrpath
  - cim-schema
  - cl-asdf
  - cmake
  - cmpi-bindings-pywbem
  - colordiff
  - common-lisp-controller
  - compat-gcc-44
  - compat-gcc-44-c++
  - compat-poppler022
  - compat-poppler022-qt
  - createrepo_c
  - createrepo_c-libs
  - cube
  - cube-devel
  - cube-libs
  - cups-devel
  - cvs
  - cvsps
  - cyrus-sasl-devel
  - darcs
  - dbus-devel
  - dbus-glib-devel
  - dbusmenu-qt
  - dejagnu
  - distribution-gpg-keys
  - docbook-dtds
  - docbook-style-xsl
  - e2fsprogs-devel
  - easymock2
  - elfutils-devel
  - elfutils-libelf-devel
  - evolution-data-server-devel
  - expat-devel
  - expect
  - flute
  - fontconfig-devel
  - freeglut
  - freeglut-devel
  - freerdp
  - freerdp-plugins
  - freetype-devel
  - fuse-devel
  - gamin
  - gc
  - gcc-gnat
  - gcc-objc
  - gcc-objc++
  - gcr-devel
  - gdk-pixbuf2-devel
  - geronimo-jms
  - ghc
  - ghc-Cabal
  - ghc-Cabal-devel
  - ghc-GLURaw
  - ghc-GLURaw-devel
  - ghc-GLUT
  - ghc-GLUT-devel
  - ghc-HTTP
  - ghc-HTTP-devel
  - ghc-HUnit
  - ghc-HUnit-devel
  - ghc-OpenGL
  - ghc-OpenGL-devel
  - ghc-OpenGLRaw
  - ghc-OpenGLRaw-devel
  - ghc-QuickCheck
  - ghc-QuickCheck-devel
  - ghc-array
  - ghc-array-devel
  - ghc-async
  - ghc-async-devel
  - ghc-attoparsec
  - ghc-attoparsec-devel
  - ghc-base
  - ghc-base-devel
  - ghc-binary
  - ghc-binary-devel
  - ghc-bytestring
  - ghc-bytestring-devel
  - ghc-case-insensitive
  - ghc-case-insensitive-devel
  - ghc-cgi
  - ghc-cgi-devel
  - ghc-compiler
  - ghc-containers
  - ghc-containers-devel
  - ghc-dataenc
  - ghc-deepseq
  - ghc-deepseq-devel
  - ghc-directory
  - ghc-directory-devel
  - ghc-doc-index
  - ghc-extensible-exceptions
  - ghc-fgl
  - ghc-fgl-devel
  - ghc-filepath
  - ghc-filepath-devel
  - ghc-ghc
  - ghc-ghc-devel
  - ghc-hashable
  - ghc-hashable-devel
  - ghc-hashed-storage
  - ghc-haskeline
  - ghc-haskell-platform-devel
  - ghc-haskell-src
  - ghc-haskell-src-devel
  - ghc-haskell2010
  - ghc-haskell2010-devel
  - ghc-haskell98
  - ghc-haskell98-devel
  - ghc-hoopl
  - ghc-hoopl-devel
  - ghc-hpc
  - ghc-hpc-devel
  - ghc-html
  - ghc-html-devel
  - ghc-libraries
  - ghc-mmap
  - ghc-mtl
  - ghc-mtl-devel
  - ghc-network
  - ghc-network-devel
  - ghc-old-locale
  - ghc-old-locale-devel
  - ghc-old-time
  - ghc-old-time-devel
  - ghc-parallel
  - ghc-parallel-devel
  - ghc-parsec
  - ghc-parsec-devel
  - ghc-pretty
  - ghc-pretty-devel
  - ghc-primitive
  - ghc-primitive-devel
  - ghc-process
  - ghc-process-devel
  - ghc-random
  - ghc-random-devel
  - ghc-regex-base
  - ghc-regex-base-devel
  - ghc-regex-compat
  - ghc-regex-compat-devel
  - ghc-regex-posix
  - ghc-regex-posix-devel
  - ghc-split
  - ghc-split-devel
  - ghc-stm
  - ghc-stm-devel
  - ghc-syb
  - ghc-syb-devel
  - ghc-tar
  - ghc-template-haskell
  - ghc-template-haskell-devel
  - ghc-terminfo
  - ghc-text
  - ghc-text-devel
  - ghc-time
  - ghc-time-devel
  - ghc-transformers
  - ghc-transformers-devel
  - ghc-unix
  - ghc-unix-devel
  - ghc-unordered-containers
  - ghc-unordered-containers-devel
  - ghc-utf8-string
  - ghc-vector
  - ghc-vector-devel
  - ghc-xhtml
  - ghc-xhtml-devel
  - ghc-zlib
  - ghc-zlib-devel
  - gl-manpages
  - glib2-devel
  - gmp-devel
  - gnome-desktop3-devel
  - gnome-online-accounts-devel
  - gnucash
  - gnucash-docs
  - gnutls-c++
  - gnutls-dane
  - gnutls-devel
  - gobject-introspection-devel
  - goffice08
  - graphite2-devel
  - gsettings-desktop-schemas-devel
  - gstreamer1-devel
  - gstreamer1-plugins-base-devel
  - gtk2-devel
  - gtk3-devel
  - guile
  - gvfs-devel
  - gwenhywfar
  - gwenhywfar-gui-gtk2
  - hamcrest
  - happy
  - harfbuzz-devel
  - haskell-platform
  - hmaccalc
  - httpd
  - httpd-devel
  - httpd-tools
  - hunspell-devel
  - ibacm
  - icoutils
  - ilmbase
  - imake
  - iptables-devel
  - jakarta-commons-httpclient
  - javamail
  - json-glib-devel
  - junit
  - kactivities
  - kate-part
  - kde-filesystem
  - kde-runtime
  - kde-runtime-drkonqi
  - kde-runtime-libs
  - kde-settings
  - kde-style-oxygen
  - kde-workspace-devel
  - kde-workspace-libs
  - kdegraphics-devel
  - kdegraphics-libs
  - kdelibs
  - kdelibs-common
  - kdelibs-devel
  - kdelibs-ktexteditor
  - kdenetwork-common
  - kdenetwork-devel
  - kdenetwork-kopete
  - kdenetwork-kopete-devel
  - kdenetwork-kopete-libs
  - kdenetwork-krdc
  - kdenetwork-krdc-devel
  - kdenetwork-krdc-libs
  - kdepim
  - kdepim-devel
  - kdepim-libs
  - kdepim-runtime
  - kdepim-runtime-libs
  - kdepimlibs
  - kdepimlibs-akonadi
  - kdepimlibs-devel
  - kdepimlibs-kxmlrpcclient
  - kdesdk-common
  - kdesdk-devel
  - kdesdk-kmtrace
  - kdesdk-kmtrace-devel
  - kdesdk-kmtrace-libs
  - kdesdk-kompare
  - kdesdk-kompare-devel
  - kdesdk-kompare-libs
  - kdesdk-okteta
  - kdesdk-okteta-devel
  - kdesdk-okteta-libs
  - keyutils-libs-devel
  - konkretcmpi
  - konkretcmpi-python
  - krb5-devel
  - ksc
  - ksysguard-libs
  - ktoblzcheck
  - kwin-gles-libs
  - kwin-libs
  - libICE-devel
  - libSM-devel
  - libX11-devel
  - libXScrnSaver
  - libXScrnSaver-devel
  - libXau-devel
  - libXaw
  - libXaw-devel
  - libXcomposite-devel
  - libXcursor-devel
  - libXdamage-devel
  - libXext-devel
  - libXfixes-devel
  - libXft-devel
  - libXi-devel
  - libXinerama-devel
  - libXmu-devel
  - libXp
  - libXp-devel
  - libXpm-devel
  - libXrandr-devel
  - libXrender-devel
  - libXt-devel
  - libXtst-devel
  - libXv-devel
  - libXxf86misc-devel
  - libXxf86vm-devel
  - libacl-devel
  - libaio-devel
  - libart_lgpl
  - libatomic
  - libatomic-static
  - libattr-devel
  - libbase
  - libblkid-devel
  - libcanberra-devel
  - libcap-devel
  - libcap-ng-devel
  - libcom_err-devel
  - libcurl-devel
  - libdbi
  - libdrm-devel
  - libepoxy-devel
  - libffi-devel
  - libfonts
  - libformula
  - libgcrypt-devel
  - libgdata-devel
  - libgnat
  - libgnat-devel
  - libgnome-keyring-devel
  - libgnomecanvas
  - libgpg-error-devel
  - libgudev1-devel
  - libgweather-devel
  - libhugetlbfs
  - libhugetlbfs-devel
  - libibcm
  - libibumad
  - libical-devel
  - libicu-devel
  - libieee1284-devel
  - libiodbc
  - libitm
  - libitm-devel
  - libjpeg-turbo-devel
  - libkdcraw
  - libkdcraw-devel
  - libkexiv2
  - libkexiv2-devel
  - libkipi
  - libkipi-devel
  - libksane
  - libksane-devel
  - libkworkspace
  - liblayout
  - libloader
  - libmsn
  - libnl-devel
  - libnotify-devel
  - liboauth-devel
  - libobjc
  - libofx
  - libpfm
  - libpfm-devel
  - libpng-devel
  - libreoffice-base
  - libreoffice-ogltrans
  - libreoffice-wiki-publisher
  - librepository
  - librsvg2-devel
  - libsecret-devel
  - libselinux-devel
  - libsepol-devel
  - libserializer
  - libsoup-devel
  - libstdc++-docs
  - libtasn1-devel
  - libtiff-devel
  - libusbx-devel
  - libuuid-devel
  - libverto-devel
  - libvncserver
  - libxcb-devel
  - libxkbfile-devel
  - libxml2-devel
  - libxslt-devel
  - lm_sensors-devel
  - log4j
  - lzo-minilzo
  - mariadb-devel
  - mercurial
  - mesa-libEGL-devel
  - mesa-libGL-devel
  - mesa-libGLU-devel
  - mock
  - mock-core-configs
  - mod_dav_svn
  - motif
  - motif-devel
  - mpfr-devel
  - nasm
  - ncurses-devel
  - nepomuk-core
  - nepomuk-core-devel
  - nepomuk-core-libs
  - net-snmp-agent-libs
  - net-snmp-devel
  - nettle-devel
  - nspr-devel
  - nss-devel
  - nss-softokn-devel
  - nss-softokn-freebl-devel
  - nss-util-devel
  - numactl-devel
  - ocaml
  - ocaml-compiler-libs
  - ocaml-runtime
  - okular-devel
  - okular-libs
  - openldap-devel
  - openlmi-providers
  - openlmi-providers-devel
  - openlmi-python-base
  - openslp
  - opensp
  - openssl-devel
  - ortp
  - otf2
  - otf2-devel
  - oxygen-icon-theme
  - p11-kit-devel
  - pango-devel
  - papi
  - papi-devel
  - pcre-devel
  - pentaho-libxml
  - pentaho-reporting-flow-engine
  - perl-Algorithm-Diff
  - perl-App-cpanminus
  - perl-Archive-Zip
  - perl-BZ-Client
  - perl-CPAN-Meta
  - perl-CPAN-Meta-Requirements
  - perl-CPAN-Meta-YAML
  - perl-Class-Factory-Util
  - perl-Class-Load
  - perl-Class-Singleton
  - perl-Data-OptList
  - perl-Date-Manip
  - perl-DateTime
  - perl-DateTime-Format-Builder
  - perl-DateTime-Format-ISO8601
  - perl-DateTime-Format-Strptime
  - perl-DateTime-Locale
  - perl-DateTime-TimeZone
  - perl-Devel-Symdump
  - perl-Digest-SHA1
  - perl-ExtUtils-CBuilder
  - perl-Finance-Quote
  - perl-Font-AFM
  - perl-HTML-Element-Extended
  - perl-HTML-Format
  - perl-HTML-TableExtract
  - perl-HTML-Tree
  - perl-IPC-Cmd
  - perl-JSON
  - perl-JSON-PP
  - perl-LWP-Protocol-https
  - perl-List-MoreUtils
  - perl-Locale-Maketext-Simple
  - perl-Module-Build
  - perl-Module-CoreList
  - perl-Module-Implementation
  - perl-Module-Load
  - perl-Module-Load-Conditional
  - perl-Module-Metadata
  - perl-Module-Runtime
  - perl-Module-Signature
  - perl-Mozilla-CA
  - perl-PAR-Dist
  - perl-Package-DeprecationManager
  - perl-Package-Stash
  - perl-Package-Stash-XS
  - perl-Params-Check
  - perl-Params-Util
  - perl-Params-Validate
  - perl-Parse-CPAN-Meta
  - perl-Perl-OSType
  - perl-Pod-Coverage
  - perl-Sub-Install
  - perl-Test-Pod
  - perl-Test-Pod-Coverage
  - perl-Text-Diff
  - perl-Time-Piece
  - perl-Try-Tiny
  - perl-XML-Writer
  - perl-YAML
  - perl-YAML-Tiny
  - perl-homedir
  - perl-version
  - perltidy
  - phonon
  - phonon-backend-gstreamer
  - phonon-devel
  - pidgin
  - pigz
  - pixman-devel
  - polkit-devel
  - polkit-docs
  - polkit-qt
  - popt-devel
  - postgresql
  - postgresql-devel
  - postgresql-jdbc
  - postgresql-libs
  - pulseaudio-libs-devel
  - pygobject3-devel
  - python-BeautifulSoup
  - python-Levenshtein
  - python-beaker
  - python-devel
  - python-docs
  - python-enchant
  - python-genshi
  - python-mako
  - python-paste
  - python-tempita
  - python-vobject
  - python2-distro
  - python2-pyroute2
  - python2-simplejson
  - pywbem
  - qca-ossl
  - qca2
  - qdox
  - qgit
  - qimageblitz
  - qjson
  - qt-devel
  - qt-mysql
  - qt-odbc
  - qt-postgresql
  - qt3-MySQL
  - qt3-ODBC
  - qt3-PostgreSQL
  - qt5-qtbase
  - qt5-qtbase-common
  - qt5-qtbase-gui
  - qt5-qtsvg
  - rdma-core-devel
  - readline-devel
  - redland-virtuoso
  - rpm-devel
  - rpmdevtools
  - rpmlint
  - sac
  - sane-backends-devel
  - sane-backends-drivers-cameras
  - sbcl
  - scorep
  - scorep-libs
  - sgml-common
  - shared-desktop-ontologies
  - shared-desktop-ontologies-devel
  - sip
  - sip-devel
  - sip-macros
  - soprano
  - soprano-devel
  - sqlite-devel
  - startup-notification-devel
  - strigi-libs
  - subversion-gnome
  - systemd-devel
  - systemtap-server
  - tbb
  - tbb-devel
  - tcl
  - tcl-devel
  - tcp_wrappers-devel
  - tk
  - tk-devel
  - tog-pegasus
  - tog-pegasus-libs
  - tomcat-servlet-3.0-api
  - trac
  - trac-mercurial-plugin
  - translate-toolkit
  - unique3
  - unique3-devel
  - unixODBC
  - unixODBC-devel
  - usermode-gtk
  - virtuoso-opensource
  - vym
  - webkitgtk
  - webkitgtk4-devel
  - webkitgtk4-jsc-devel
  - xalan-j2
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xerces-j2
  - xml-commons-apis
  - xml-commons-resolver
  - xmlsec1-gcrypt
  - xmlsec1-gnutls
  - xorg-x11-proto-devel
  - xorg-x11-xbitmaps
  - xz-devel
  - zlib-devel
  - gtkspell
  - java-1.8.0-openjdk-devel
  - m2crypto
  - python-magic