---
domain: dinohead.ninja
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: "credssp"

hyperV:
  storagePath: C:\ClusterStorage\cluster-storage-01\vm
  template:
    ubuntuServer1604: C:\ClusterStorage\cluster-storage-01\vhdx-templates\ubuntu-server-1604.vhdx
    ubuntuDesktop1604: C:\ClusterStorage\cluster-storage-01\vhdx-templates\ubuntu-desktop-1604.vhdx